### ISSUE TITLE
After Login Nothing Happens

### ISSUE THREAD

**Issue by MusheAbdulHakim** [swaaz/InstaBot#30]
Traceback (most recent call last):
  File "program.py", line 239, in <module>
    main()
  File "program.py", line 218, in main
    bot = Instabot(username,password)
  File "program.py", line 35, in __init__
    self._make_driver_wait("//button[contains(text(), 'Not Now')]")
  File "program.py", line 209, in _make_driver_wait
    wait.until(EC.element_to_be_clickable((By.XPATH, element_to_locate)))
  File "/usr/lib/python3/dist-packages/selenium/webdriver/support/wait.py", line 86, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Mesalcode** [comment]
Might be a captcha

**Comment by swaaz** [comment]
@MusheAbdulHakim @Mesalcode I fixed all the bugs. The issue was due to chnage in UI of Insagram webiste.
